[2023-07-21 15:21:56,281:INFO:main:welcome to my custom log:]
[2023-07-22 16:26:52,020:INFO:common:yaml file:config\config.yaml is loaded succesfully:]
[2023-07-22 16:26:52,029:INFO:common:yaml file:params.yaml is loaded succesfully:]
[2023-07-22 16:32:25,359:INFO:common:yaml file:config\config.yaml is loaded succesfully:]
[2023-07-22 16:32:25,366:INFO:common:yaml file:params.yaml is loaded succesfully:]
[2023-07-22 16:36:00,160:INFO:common:yaml file:config\config.yaml is loaded succesfully:]
[2023-07-22 16:36:00,164:INFO:common:yaml file:params.yaml is loaded succesfully:]
[2023-07-25 18:21:14,103:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2023-07-25 18:21:14,115:INFO:common:yaml file: params.yaml loaded successfully:]
[2023-07-25 18:22:20,013:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2023-07-25 18:22:20,022:INFO:common:yaml file: params.yaml loaded successfully:]
[2023-07-25 18:53:45,667:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2023-07-25 18:53:45,671:INFO:common:yaml file: params.yaml loaded successfully:]
[2023-07-25 18:54:03,177:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2023-07-25 18:54:03,185:INFO:common:yaml file: params.yaml loaded successfully:]
[2023-07-25 18:54:03,188:INFO:common:created directory at: artifacts:]
[2023-07-25 18:54:03,191:INFO:common:created directory at: artifacts/data_ingestion:]
[2023-07-25 19:10:15,137:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2023-07-25 19:10:15,140:INFO:common:yaml file: params.yaml loaded successfully:]
[2023-07-25 19:10:15,142:INFO:common:created directory at: artifacts:]
[2023-07-25 19:10:15,144:INFO:common:created directory at: artifacts/data_ingestion:]
[2023-07-25 19:24:02,429:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2023-07-25 19:24:02,431:INFO:common:yaml file: params.yaml loaded successfully:]
[2023-07-25 19:24:02,434:INFO:common:created directory at: artifacts:]
[2023-07-25 19:24:02,435:INFO:common:created directory at: artifacts/data_ingestion:]
[2023-07-25 19:26:33,310:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2023-07-25 19:26:33,316:INFO:common:yaml file: params.yaml loaded successfully:]
[2023-07-25 19:26:33,318:INFO:common:created directory at: artifacts:]
[2023-07-25 19:26:33,318:INFO:common:created directory at: artifacts/data_ingestion:]
[2023-07-25 19:26:33,321:INFO:1552846254:File already exists of size:~ 11345 KB:]
[2023-07-25 20:44:59,388:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<:]
[2023-07-25 20:44:59,388:ERROR:main:get_data_ingestion_config() missing 1 required positional argument: 'self':]
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    data_ingestion.main()
  File "d:\chicken disease classifiation\chicken_disease_classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 13, in main
    data_ingestion_config=config.get_data_ingestion_config()
TypeError: get_data_ingestion_config() missing 1 required positional argument: 'self'
[2023-07-25 20:47:54,825:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<:]
[2023-07-25 20:47:54,825:ERROR:main:'DataIngestionTrainingPipeline' object has no attribute 'config':]
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    data_ingestion.main()
  File "d:\chicken disease classifiation\chicken_disease_classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 13, in main
    data_ingestion_config=config.get_data_ingestion_config(self)
  File "d:\chicken disease classifiation\chicken_disease_classification\src\cnnClassifier\config\configuration.py", line 19, in get_data_ingestion_config
    config = self.config.data_ingestion
AttributeError: 'DataIngestionTrainingPipeline' object has no attribute 'config'
[2023-07-25 20:50:17,690:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<:]
[2023-07-25 20:50:17,693:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2023-07-25 20:50:17,694:INFO:common:yaml file: params.yaml loaded successfully:]
[2023-07-25 20:50:17,696:INFO:common:created directory at: artifacts:]
[2023-07-25 20:50:17,698:INFO:common:created directory at: artifacts/data_ingestion:]
[2023-07-25 20:50:17,746:ERROR:main:<urlopen error [Errno 11001] getaddrinfo failed>:]
Traceback (most recent call last):
  File "C:\Users\satis\anaconda3\envs\chicken\lib\urllib\request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\satis\anaconda3\envs\chicken\lib\http\client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\satis\anaconda3\envs\chicken\lib\http\client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\satis\anaconda3\envs\chicken\lib\http\client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\satis\anaconda3\envs\chicken\lib\http\client.py", line 1011, in _send_output
    self.send(msg)
  File "C:\Users\satis\anaconda3\envs\chicken\lib\http\client.py", line 951, in send
    self.connect()
  File "C:\Users\satis\anaconda3\envs\chicken\lib\http\client.py", line 1418, in connect
    super().connect()
  File "C:\Users\satis\anaconda3\envs\chicken\lib\http\client.py", line 922, in connect
    self.sock = self._create_connection(
  File "C:\Users\satis\anaconda3\envs\chicken\lib\socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\satis\anaconda3\envs\chicken\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    data_ingestion.main()
  File "d:\chicken disease classifiation\chicken_disease_classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "d:\chicken disease classifiation\chicken_disease_classification\src\cnnClassifier\components\data_ingestion.py", line 15, in download_file
    filename,headers=request.urlretrieve(
  File "C:\Users\satis\anaconda3\envs\chicken\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\satis\anaconda3\envs\chicken\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\satis\anaconda3\envs\chicken\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\satis\anaconda3\envs\chicken\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\satis\anaconda3\envs\chicken\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\satis\anaconda3\envs\chicken\lib\urllib\request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\satis\anaconda3\envs\chicken\lib\urllib\request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>
[2023-07-25 20:53:07,475:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<:]
[2023-07-25 20:53:07,479:INFO:common:yaml file: config\config.yaml loaded successfully:]
[2023-07-25 20:53:07,480:INFO:common:yaml file: params.yaml loaded successfully:]
[2023-07-25 20:53:07,482:INFO:common:created directory at: artifacts:]
[2023-07-25 20:53:07,484:INFO:common:created directory at: artifacts/data_ingestion:]
[2023-07-25 20:53:28,927:INFO:data_ingestion:artifacts/data_ingestion/data.zip download with following info:
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 1A6C:45FF:8A953:9BB78:64BFE8DC
Accept-Ranges: bytes
Date: Tue, 25 Jul 2023 15:23:11 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10223-MAA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1690298589.193221,VS0,VE2067
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 0209959e3191a20874f908c5ce65846127c0413a
Expires: Tue, 25 Jul 2023 15:28:11 GMT
Source-Age: 2

:]
[2023-07-25 20:53:29,290:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x:]
